<a href="https://colab.research.google.com/github/AYSHOTRAX/VOR.DS-Test-/blob/main/Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = 'Ayush' #This is my name
print(a)


Ayush


In [ ]:
str('Dashant') #structure
age = 22
percent = 90.2
print(age)
type(percent)
type(age)

22


int

In [ ]:
student1= ('ishika', 22, 90.2) #tuple
student2= ['ishika', 22, 90.2] #list
student3= {'ishika', 22, 90.2} #set creates random output
type(student3)

set

In [ ]:
print(student3)

{90.2, 'ishika', 22}


In [ ]:
range(10)
student={ 'Name':'Ishika','Age': 22,'Percent': 90.2}
student

{'Name': 'Ishika', 'Age': 22, 'Percent': 90.2}

In [ ]:
student.values

<function dict.values>

In [ ]:
bool(-1)

True

In [ ]:
fruits =['apple','cherry','banana']
fruits.append('orange')
fruits.sort()
fruits.reverse()
fruits.remove('banana')
fruits.pop(1)
fruits.insert(1,'Watermelon')
fruits.index('Watermelon')
others=['pineapple','strawberry','guava','cherry']
fruits.extend(others)
fruits.count('cherry')
fruits.copy()
fruits.clear()


In [ ]:
fruits


[]

In [ ]:
#string methods
txt = "hello, I am Ayush."
a = txt.capitalize()
print(a)
txt = "I am from Ghaziabad and born in Guwahati,India."
b = txt.count("Ghaziabad")
print(b)
txt = "I love apples, apple are my favorite fruit"
c = txt.find("apple")
print(c)
d = txt.index("apple")
print(d)
txt = "hello, my name is Ayush, I am 22 years old"
e = txt.split()
print(e)

Hello, i am ayush.
1
7
7
['hello,', 'my', 'name', 'is', 'Ayush,', 'I', 'am', '22', 'years', 'old']


In [ ]:
txt = "Company12" #
name = txt.isalnum()
print(name)
txt = "CompanyX"
alpha = txt.isalpha()
print(alpha)
txt = '50000'
num = txt.isdigit()
print(num)
names = ["Prashant", "Waqar", "Vinay"]
joined = "$".join(names)
print(joined)
txt = "I love aalo"
result = txt.replace("aalo", "bhaloo")
print(result)
txt = "Hello, welcome to the jungle."
start = txt.startswith("Hello")
end = txt.endswith(".")


True
True
True
Prashant$Waqar$Vinay
I love bhaloo


In [ ]:
start, end

(True, True)

In [ ]:
#conditional statements (if,elif,else)
a, b = 33, 200
print(b>a)

if b>a:
  print("b is greater than a")

True
b is greater than a


In [ ]:
aman , vinod = 60 , 62
if vinod > aman:
  print("vinod scores greater than aman")
elif aman == vinod:
  print("Both scores equally")

vinod scores greater than aman


In [ ]:
if vinod > aman:
  print("vinod scores greater than aman")
elif aman == vinod:
    print(" Both scores equally")

vinod scores greater than aman


In [ ]:
def my_function():                      #Function Definig
  print("Hello i'm a Bioinformatician")

In [ ]:
my_function()                           #Function calling

Hello i'm a Bioinformatician


In [ ]:
def my_ID(name):                        #Function with Arguments
  print("CR001_" + name)

  my_ID("Onkar")

In [ ]:
def add(a,b,c):
  add =lambda a,b,c: print(a+b+c)
add(4,5,5)

In [ ]:
#Map function
nums = [1, 2, 3, 4, 5]

def sq(n):
   return n*n

   square = map(sq, nums)
   print(list(square))


In [ ]:
#Zip function
name = ["Manjeet", "Nikhil", "Shambhavi"]
ID = [4, 1, 3]
mapped = zip(name, ID)
print(list(mapped))

[('Manjeet', 4), ('Nikhil', 1), ('Shambhavi', 3)]


In [ ]:
#Python loops
fruits = ["apple", "banana", "cherry", "pineapple", "mango"]
for x in fruits:
 print(x)

apple
banana
cherry
pineapple
mango


In [ ]:
num = 1
while num < 6:
  print(num)
  num += 1

1
2
3
4
5


In [ ]:
num = 1
while num < 32:
  print(num)
  num += 5

1
6
11
16
21
26
31


In [ ]:
num = 0

while num < 6:
  num += 1
  if num == 3:
    continue
  print(num)

1
2
4
5
6


In [ ]:
fruits = ("apples", "banana", "pineapple", "banana")
print(fruits)

('apples', 'banana', 'pineapple', 'banana')


In [ ]:
nums = (1, 2, 3, 4, 6, 7, 8, 6)
nums.count(6)

2

In [ ]:
nums = (1, 2, 3, 4, 6, 7, 8, 6)
nums.index(6)

4

In [ ]:
nums = (1, 2, 3, 4, 6, 7, 8, 6)

min(nums)
#max(nums)

1

In [ ]:
#Dictionaries, they have keys:values pair.
#Ordered, changeable, no duplicates.
car = {"brand": "Ford", "model": "Mustang", "year": 1964}
#car.get("brand")
car.items()
car.keys()
car.values()



dict_values(['Ford', 'Mustang', 1964])

In [ ]:
#car.pop("year")
#print(car)
car.popitem()
print(car)


{'brand': 'Ford', 'model': 'Mustang'}


In [ ]:
car.update({"color": "white"})
print(car)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'white'}


In [ ]:
car.clear()
print(car)

{}


In [61]:
fruits = {"apple", "banana", "cherry"}
fruits.add("orange")
print(fruits)

{'orange', 'banana', 'apple', 'cherry'}


In [59]:
#fruits.pop()
#print(fruits)

In [62]:
fruits.remove("banana")
print(fruits)

{'orange', 'apple', 'cherry'}


In [1]:
import numpy as np # importing numpy library

In [2]:
A = np.array(5) #Scalar Array
A

array(5)

In [3]:
np.ndim(A)  # Dimension method

0

In [7]:
One = np.array([1, 2, 3, 4, 5])
One

array([1, 2, 3, 4, 5])

In [9]:
Two = np.array([[2, 3, 4], [5, 6, 7]])
Two

array([[2, 3, 4],
       [5, 6, 7]])

In [10]:
Three = np.array([[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]])
Three

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [11]:
np.ndim(Three)

3

In [2]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3.9,'apple'])

In [5]:
arr

array(['1', '2', '3.9', 'apple'], dtype='<U32')

In [7]:
arr = np.array([1, 2, 3, 6, 9])
arr*5

array([ 5, 10, 15, 30, 45])

In [ ]:
#Array Reshaping

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)


In [11]:
newarr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [16]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 0, 2 ])

3


In [19]:
a1 = np.array([1, 2, 3, 4, 5, 6, 7])
#a1[1:5]
#a1[4:]
a1[:2]

array([1, 2])

In [1]:
import numpy as np

In [5]:
a2 = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
#a2[1, 1:4]
#a2[0:2, 2]
a2[0:2, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [9]:
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])

In [18]:
a3[:1, 2:3, :2]

array([[[16, 17]]])

In [22]:
#copy is a new array and view of the original array
arr = np.array([1, 2, 3, 4, 5])

copy = arr.copy()
copy[0] = 42
print(arr)
print(copy)


[1 2 3 4 5]
[42  2  3  4  5]


In [47]:
import numpy as np

In [55]:
#Append, Insert, Delete (numpy)
a = np.array([[1, 2, 3],
             [4, 5, 6]])
#np.append(a, [[7, 8, 9]], axis = 0)
np.append(a, [[5], [8]], axis = 1)

array([[1, 2, 3, 5],
       [4, 5, 6, 8]])

In [23]:
import pandas as pd
#Panda Series

In [25]:
#Series Method
series = pd.Series([31, 27, 52, 88, 75])
print(series)

0    31
1    27
2    52
3    88
4    75
dtype: int64


In [27]:
# Series Method with Index
series = pd.Series([1, 7, 2, 8, 5], index = ["a", "b", "c", "d", "e"])
print(series)

a    1
b    7
c    2
d    8
e    5
dtype: int64


In [28]:
print(series["a"])

1


In [29]:
print(series["d"])

8


In [4]:
import pandas as pd

In [6]:
data = pd.DataFrame({'Name':['Tom', 'Jack', 'Steve', 'Ricky', 'Sam', 'Will', 'Root'],
                     'Age':[28, 34, 29, 42, 17, 17, 45 ]})
data.head(10) #head by default takes 5 values so here we take 10

Name  Age
0    Tom   28
1   Jack   34
2  Steve   29
3  Ricky   42
4    Sam   17
5   Will   17
6   Root   45

from matplotlib import pyplot as plt
_df_4['Age'].plot(kind='hist', bins=20, title='Age')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_5.groupby('Name').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6['Age'].plot(kind='line', figsize=(8, 4), title='Age')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_7['Name'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_7, x='Age', y='Name', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [45]:
data = pd.DataFrame({'Name':['Tom', 'Jack', 'Steve', 'Ricky', 'Sam', 'Will', 'Root'],
                     'Age':[28, 34, 29, 42, 17, 17, 45 ]}, index= [1., 2., 3., 4., 5., 6., 7.])
data.head(10)

Name  Age
1.0    Tom   28
2.0   Jack   34
3.0  Steve   29
4.0  Ricky   42
5.0    Sam   17
6.0   Will   17
7.0   Root   45

In [46]:
data [data['Age'] <=18][['Name']]

Name
5.0   Sam
6.0  Will

In [2]:
import pandas as pd

In [9]:
data = pd.DataFrame({'Name':['Ayush', 'Waqar', 'Vinay', 'Prashant', 'Naveen'],
                     'Marks' :[88, 79, 75, 83, 77]}, index=['C1', 'C2', 'C3', 'C4', 'C5'])
data.head()

Name  Marks
C1     Ayush     88
C2     Waqar     79
C3     Vinay     75
C4  Prashant     83
C5    Naveen     77

from matplotlib import pyplot as plt
_df_10['Marks'].plot(kind='hist', bins=20, title='Marks')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_11.groupby('Name').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_12['Marks'].plot(kind='line', figsize=(8, 4), title='Marks')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_13['Name'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_13, x='Marks', y='Name', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [14]:
#Column selection in pandas
data['Name']
data['Marks']

C1    88
C2    79
C3    75
C4    83
C5    77
Name: Marks, dtype: int64

In [13]:
# Row Selection
data.loc['C2', 'Name']

'Waqar'

In [15]:
data.iloc[0, 0]

'Ayush'

In [ ]:
#Concatenation of Pandas
#used to concatenate pandas objects(Dataframes) along a particular axis(Horizontal,Vertical)

In [30]:
names = pd.DataFrame({'Name': ['Tom', 'Jack', 'Steve', 'Ricky', 'Sam', 'Will', 'Root']})
ages = pd.DataFrame({'Age' :[28, 34, 29, 42, 17, 17, 45]})

In [31]:
names2 = pd.DataFrame({'Name' :['Joe', 'Pope', 'Buttler', 'Ben', 'James', 'Cook']})

In [24]:
sales = pd.DataFrame({'Status' :['+', '-', '-', '+', '-', '+', '-']})

In [39]:
pd.concat([names, names2], axis= 0).reset_index()

index     Name
0       0      Tom
1       1     Jack
2       2    Steve
3       3    Ricky
4       4      Sam
5       5     Will
6       6     Root
7       0      Joe
8       1     Pope
9       2  Buttler
10      3      Ben
11      4    James
12      5     Cook

In [1]:
import pandas as pd


In [2]:
data = pd.DataFrame({
    'Name': ['Ankit', 'Aishwarya', 'Sanket', 'Shivangi', 'Saiprasad', 'Rishika', 'Pratiksha'],
    'Age' : [23, 21, 22, 21, 22, 21, 20],
    'University' :['BHU', 'JNU', 'DU', 'BHU', 'SPPU', 'SPPU', 'DU'],})

In [4]:
data

Name  Age University
0      Ankit   23        BHU
1  Aishwarya   21        JNU
2     Sanket   22         DU
3   Shivangi   21        BHU
4  Saiprasad   22       SPPU
5    Rishika   21       SPPU
6  Pratiksha   20         DU

In [5]:
data.to_csv('students.csv')

In [ ]:
new_data = pd.read_csv('/content/students.csv')